
[target.'cfg(target_os = "macos")']
rustflags = [
    # use lld instead of ld, because the default linker throws some errors: specifically `-lSystem not found`
    "-C",
    "link-arg=-fuse-ld=lld",
]
